---
# tasks file for cockpit
# Variable configuration.
- include_tasks: variables.yml
# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
- name: Ensure Cockpit Web Console is started and enabled on boot.
  service:
    name: "{{ cockpit_daemon }}"
    state: started
    enabled: yes
