---
- name: Ensure Cockpit Web Console packages are installed.
  #package:
  dnf:
    name: "{{ cockpit_packages }}"
    state: present
    enablerepo: "{{ cockpit_enablerepo | default(omit, true) }}"
