---
# Variable configuration.
- name: Include OS-specific variables (RedHat RHEL 7).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- name: Include OS-specific variables (RedHat RHEL 8).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
#  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version > '8'

- name: Include OS-specific variables (Fedora).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
#  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'Fedora'

- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
#  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Define cockpit_daemon.
  set_fact:
    cockpit_daemon: "{{ __cockpit_daemon }}"
  when: cockpit_daemon is not defined

#- name: Define cockpit_packages.
#  set_fact:
#    cockpit_packages: "{{ __cockpit_packages | list }}"



