---
__cockpit_daemon: cockpit
__cockpit_packages:
  default:
    - cockpit
    - cockpit-networkmanager
    - cockpit-packagekit
    - cockpit-selinux
    - cockpit-storaged
    - cockpit-system
  minimal: "cockpit"
  full: "cockpit*"
__cockpit_packages_exclude:
  - cockpit-docker   # omit in favor of podman
  - cockpit-ostree   # omit only needed for CoreOS
  - cockpit-tests    # omit only needed for testing
